openapi: 3.0.3
info:
  title: Library API
  version: 1.2.0
  description: STD22001
servers:
  - url: https://library.com
tags:
  - name: Books
  - name: Authors 
paths:
  /books:
    get:
      tags:
        - Books
      summary: Get all books
      description: The returned books are ordered by updated datetime.
      operationId: getBooks
      parameters:
        - in: query
          name: page
          schema:
            $ref: '#/components/parameters/QueryPagination/schema/properties/page'
        - in: query
          name: pagesize
          schema:
            $ref: '#/components/parameters/QueryPagination/schema/properties/page_size'
    
        - in: query
          name: bookName
          description: Filter return books by given name
          required: false
          schema:
            type: string
        - in: query
          name: releaseDateMin
          description: If 'releaseDateMax' is note provide,'releaseDateMin' is ignored 'releaseDateMax' can not be after 'releaseDateMin'
          schema:
            type: string
            format: date
          required: false
        - in: query
          name: releaseDateMax
          description: If 'releaseDateMin' is note provide,'releaseDateMax' is ignored 'releaseDateMin' can not be after 'releaseDateMax'
          schema:
            type: string
            format: date
          required: false
      responses:
        '200':
          description: The list of filtered books
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Book'
        '400':
          $ref: '#/components/responses/400'
        '403':
          $ref: '#/components/responses/403'
        '500':
          $ref: '#/components/responses/500'
    put:
      tags:
        - Books
      summary: Create or update a list of books
      operationId: crupdateBooks
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/Book'
      responses:
        '200':
          description: The list of created or updated books
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Book'
        '400':
          $ref: '#/components/responses/400'
        '403':
          $ref: '#/components/responses/403'
        '500':
          $ref: '#/components/responses/500'

  /books/{bookId}/authors/{authorId} :
    put:
      tags:
        - Books
      summary: create or update book
      description: This operation create or update author of the book by specification id.
      operationId: crupdateBookAuthor
      parameters:
        - in: query
          name: bookId
          description: Create books by given bookId
          required: false
          schema:
            type: string
        - in: query
          name: authorId
          description: Create  books by given authorId
          schema:
            type: string
          required: false
      responses:
        '200':
          description: The list of created or updated books
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CrupdateBooks'
        '400':
          $ref: '#/components/responses/400'
        '403':
          $ref: '#/components/responses/403'
        '500':
          $ref: '#/components/responses/500'
  /books/authors  :
    put:
      tags:
        - Authors
      summary: UpdateBookAuthor 
      description: update book author. 
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/UpdateBooks'
      responses:
        '200':
          description: The list of filtered books
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/UpdateBooks'
        '400':
          $ref: '#/components/responses/400'
        '403':
          $ref: '#/components/responses/403'
        '500':
          $ref: '#/components/responses/500'
  /authors:
     get:
      summary: Get author by name
      description:  Retrieve a list of authors, optionally filtered by name.
      operationId: getByAuthorName
      tags:
        - Authors
      parameters:
        - in: query
          name: name
          description: Name to filter authors
          required: false
          schema:
            type: string
      responses:
        '200':
          description: The list of filtered books
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Author'
        '400':
          $ref: '#/components/responses/400'
        '403':
          $ref: '#/components/responses/403'
        '500':
          $ref: '#/components/responses/500'
     put:
      tags:
          - Authors
      summary: Create or update a list of authors
      operationId: crupdateAuthors
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/Author'
      responses:
        '200':
          description: The list of created or updated authors
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Author'
        '400':
          $ref: '#/components/responses/400'
        '403':
          $ref: '#/components/responses/403'
        '500':
          $ref: '#/components/responses/500'
  /authors/page/{page}/pagesize/{pagesize}:
     get:
      summary: Get author by name
      description:  Retrieve a list of authors, optionally filtered by name.
      operationId: getByAuthorName
      tags:
        - Authors
      parameters:
        - name: page 
          in: path  
          schema:
            $ref: '#/components/parameters/QueryPagination/schema/properties/page'
          required: true
        - name: pagesize
          in: path
          schema:
            $ref: '#/components/parameters/QueryPagination/schema/properties/page_size'
          required: true
        - in: query
          name: name
          description: Name to filter authors
          required: false
          schema:
            type: string
      responses:
        '200':
          description: The list of filtered books
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Author'
        '400':
          $ref: '#/components/responses/400'
        '403':
          $ref: '#/components/responses/403'
        '500':
          $ref: '#/components/responses/500'
  /authors/{aId}: 
    delete:
      summary: Delete an author
      operationId: deleteAuthor
      tags:
          - Authors
      parameters:
        - name: aId
          in: path
          description: Author identity to be delete
          schema:
            type: string
          required: true
      responses:
        200:
          description: Author deleted successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Author'

    
components:
  responses:
    '200':
      description: successfully
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ResponseSuccefully'
    '400':
      description: Bad request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/BadRequestException'
    '403':
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/NotAuthorizedException'
    '500':
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/InternalServerException'
  schemas:
    Book:
      type: object
      properties:
        author:
          $ref: '#/components/schemas/Author'
      allOf:
        - $ref: '#/components/schemas/CrupdateBooks' 
    Author:
      type: object
      properties:
        id:
          type: string
        name: 
          type: string
        sex:
         $ref: '#/components/schemas/Sex'
    Sex:
        type: string
        enum:
            - M
            - F  
    Topic:
        type: string
        enum:
            - ROMANCE
            - COMEDY
            - OTHER
    CrupdateBooks: 
      type: object
      properties:
        id:
          type: string
        bookName:
          type: string
        topic:
            $ref: '#/components/schemas/Topic'
        
        pageNumbers:
          $ref: '#/components/parameters/QueryPagination'
        releaseDate:
          type: string
          format: date
    UpdateBooks:
      type: object
      properties:
        bookId:
          type: string
          description: The ID of the book to update
        authorId: 
          type: string
          description: The new author ID for the book
    Exception:
      type: object
      properties:
        type:
          type: string
        message:
          type: string
    ResponseSuccefully:
      allOf:
        - $ref: '#/components/schemas/Exception'
      example:
        type: ResponseSuccefully
        message: Response  successfully
    BadRequestException:
      allOf:
        - $ref: '#/components/schemas/Exception'
      example:
        type: BadRequestException
        message: Bad request
    NotAuthorizedException:
      allOf:
        - $ref: '#/components/schemas/Exception'
      example:
        type: NotAuthorizedException
        message: Not authorized
    InternalServerException:
      allOf:
        - $ref: '#/components/schemas/Exception'
      example:
        type: InternalServerException
        message: Unexpected error
  parameters:
    QueryPagination:
      name: queryPagination
      in: query
      description: Paramètres de pagination.
      required: false
      schema:
        type: object
        properties:
          page:
            type: integer
            default: 1
            description: Le numéro de page.
          page_size:
            type: integer
            default: 50
            description: Le nombre d'éléments par page

    
    PathPagination:
      name: queryPagination
      in: path
      description: pagination parametters.
      required: true
      schema:
        type: object
        properties:
          page:
            type: integer
            default: 1
            description: page number.
          page_size:
            type: integer
            default: 50
            description: Page size

    